spring.application.name=config-server
server.port=8888

# PERFIL GIT
spring.profiles.active=git
spring.cloud.config.server.git.uri=https://github.com/aprendizproducto-JulianSevilla/config-repo
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main

# EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info,env,refresh
logging.level.root=INFO