spring.application.name=load-balancer

# Configuration Gateway-Config Server
spring.config.import=optional:configserver:http://localhost:8888

# HTTPS
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:loadbalancer-keystore.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=loadbalancer-local

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Discovery
spring.cloud.discovery.enabled=true
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Custom Gateway Filters Configuration
gateway.ratelimit.header=X-Forwarded-For
gateway.ratelimit.default-key=unknown
gateway.request-id.header=X-Request-Id
gateway.fallback.message=Servicio no disponible, intenta más tarde
gateway.content-type.allowed=application/json

# Spring Cloud Gateway

# Timeout
spring.cloud.gateway.httpclient.connect-timeout=5000
spring.cloud.gateway.httpclient.response-timeout=5s

# Spring Cloud Gateway Routes
spring.cloud.gateway.routes[0].id=clientes-service
spring.cloud.gateway.routes[0].uri=lb://clientes-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/clientes/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[0].filters[1]=RequestRateLimiter=redis-rate-limiter.replenishRate=10,redis-rate-limiter.burstCapacity=20,key-resolver=#{@userKeyResolver}
spring.cloud.gateway.routes[0].filters[2]=CircuitBreaker=name=clienteCB,fallbackUri=forward:/fallback

# Ruta para raíz
#spring.cloud.gateway.routes[2].id=root-redirect
#spring.cloud.gateway.routes[2].predicates[0]=Path=/
#spring.cloud.gateway.routes[2].uri=http://localhost:8761
#spring.cloud.gateway.routes[2].filters[0]=StripPrefix=0
#Activar solo en caso de prueba rapida local

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Logging
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=DEBUG

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Observability (OTEL)
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4317
management.zipkin.tracing.endpoint=
management.otlp.metrics.export.url=http://localhost:4317/v1/metrics
management.otlp.metrics.export.step=10s